import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Componentes/Footer";
import Header from "./Componentes/header/Header";
import Whatsapp from "./Icon/Whatsapp";
import BtnWhatsapp from "./Componentes/BtnWhatsapp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BtnWhatsapp />
        <Header />
        {children}
        <Footer />
        </body>
      
    </html>
  );
}
